if (NOT DEFINED INPUT)
    message(FATAL_ERROR "INPUT is required")
endif()

if (NOT DEFINED EXCLUDE)
    message(FATAL_ERROR "EXCLUDE is required")
endif()

if (NOT DEFINED OUTPUT)
    message(FATAL_ERROR "OUTPUT is required")
endif()

function(read_lines output path)
    file(READ "${path}" content)
    string(REPLACE "\r\n" "\n" content "${content}")
    string(REPLACE "\r" "\n" content "${content}")
    string(REPLACE ";" "\\;" content "${content}")
    string(REPLACE "\n" ";" lines "${content}")
    set("${output}" "${lines}" PARENT_SCOPE)
endfunction()

read_lines(input_lines "${INPUT}")
read_lines(exclude_lines "${EXCLUDE}")

file(WRITE "${OUTPUT}" "")
foreach(line IN LISTS input_lines)
    if (line STREQUAL "")
        continue()
    endif()
    list(FIND exclude_lines "${line}" exclude_index)
    if (exclude_index EQUAL -1)
        file(APPEND "${OUTPUT}" "${line}\n")
    endif()
endforeach()
